// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: proto/saga/v1/saga.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SagaOrchestrator_CreateSaga_FullMethodName = "/saga.v1.SagaOrchestrator/CreateSaga"
	SagaOrchestrator_StartSaga_FullMethodName  = "/saga.v1.SagaOrchestrator/StartSaga"
	SagaOrchestrator_GetSaga_FullMethodName    = "/saga.v1.SagaOrchestrator/GetSaga"
	SagaOrchestrator_ListSagas_FullMethodName  = "/saga.v1.SagaOrchestrator/ListSagas"
)

// SagaOrchestratorClient is the client API for SagaOrchestrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SagaOrchestratorClient interface {
	// Register a saga definition. Returns it in PENDING state.
	CreateSaga(ctx context.Context, in *CreateSagaRequest, opts ...grpc.CallOption) (*CreateSagaResponse, error)
	// Begin executing a PENDING saga. Steps are executed synchronously
	// in order; compensation fires automatically on step failure.
	// Returns after the saga reaches a terminal state (COMPLETED or FAILED).
	StartSaga(ctx context.Context, in *StartSagaRequest, opts ...grpc.CallOption) (*StartSagaResponse, error)
	// Retrieve current state of any saga.
	GetSaga(ctx context.Context, in *GetSagaRequest, opts ...grpc.CallOption) (*GetSagaResponse, error)
	// List sagas, optionally filtered by status.
	ListSagas(ctx context.Context, in *ListSagasRequest, opts ...grpc.CallOption) (*ListSagasResponse, error)
}

type sagaOrchestratorClient struct {
	cc grpc.ClientConnInterface
}

func NewSagaOrchestratorClient(cc grpc.ClientConnInterface) SagaOrchestratorClient {
	return &sagaOrchestratorClient{cc}
}

func (c *sagaOrchestratorClient) CreateSaga(ctx context.Context, in *CreateSagaRequest, opts ...grpc.CallOption) (*CreateSagaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSagaResponse)
	err := c.cc.Invoke(ctx, SagaOrchestrator_CreateSaga_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sagaOrchestratorClient) StartSaga(ctx context.Context, in *StartSagaRequest, opts ...grpc.CallOption) (*StartSagaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartSagaResponse)
	err := c.cc.Invoke(ctx, SagaOrchestrator_StartSaga_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sagaOrchestratorClient) GetSaga(ctx context.Context, in *GetSagaRequest, opts ...grpc.CallOption) (*GetSagaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSagaResponse)
	err := c.cc.Invoke(ctx, SagaOrchestrator_GetSaga_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sagaOrchestratorClient) ListSagas(ctx context.Context, in *ListSagasRequest, opts ...grpc.CallOption) (*ListSagasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSagasResponse)
	err := c.cc.Invoke(ctx, SagaOrchestrator_ListSagas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SagaOrchestratorServer is the server API for SagaOrchestrator service.
// All implementations must embed UnimplementedSagaOrchestratorServer
// for forward compatibility.
type SagaOrchestratorServer interface {
	// Register a saga definition. Returns it in PENDING state.
	CreateSaga(context.Context, *CreateSagaRequest) (*CreateSagaResponse, error)
	// Begin executing a PENDING saga. Steps are executed synchronously
	// in order; compensation fires automatically on step failure.
	// Returns after the saga reaches a terminal state (COMPLETED or FAILED).
	StartSaga(context.Context, *StartSagaRequest) (*StartSagaResponse, error)
	// Retrieve current state of any saga.
	GetSaga(context.Context, *GetSagaRequest) (*GetSagaResponse, error)
	// List sagas, optionally filtered by status.
	ListSagas(context.Context, *ListSagasRequest) (*ListSagasResponse, error)
	mustEmbedUnimplementedSagaOrchestratorServer()
}

// UnimplementedSagaOrchestratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSagaOrchestratorServer struct{}

func (UnimplementedSagaOrchestratorServer) CreateSaga(context.Context, *CreateSagaRequest) (*CreateSagaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSaga not implemented")
}
func (UnimplementedSagaOrchestratorServer) StartSaga(context.Context, *StartSagaRequest) (*StartSagaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartSaga not implemented")
}
func (UnimplementedSagaOrchestratorServer) GetSaga(context.Context, *GetSagaRequest) (*GetSagaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSaga not implemented")
}
func (UnimplementedSagaOrchestratorServer) ListSagas(context.Context, *ListSagasRequest) (*ListSagasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSagas not implemented")
}
func (UnimplementedSagaOrchestratorServer) mustEmbedUnimplementedSagaOrchestratorServer() {}
func (UnimplementedSagaOrchestratorServer) testEmbeddedByValue()                          {}

// UnsafeSagaOrchestratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SagaOrchestratorServer will
// result in compilation errors.
type UnsafeSagaOrchestratorServer interface {
	mustEmbedUnimplementedSagaOrchestratorServer()
}

func RegisterSagaOrchestratorServer(s grpc.ServiceRegistrar, srv SagaOrchestratorServer) {
	// If the following call panics, it indicates UnimplementedSagaOrchestratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SagaOrchestrator_ServiceDesc, srv)
}

func _SagaOrchestrator_CreateSaga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSagaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SagaOrchestratorServer).CreateSaga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SagaOrchestrator_CreateSaga_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SagaOrchestratorServer).CreateSaga(ctx, req.(*CreateSagaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SagaOrchestrator_StartSaga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSagaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SagaOrchestratorServer).StartSaga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SagaOrchestrator_StartSaga_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SagaOrchestratorServer).StartSaga(ctx, req.(*StartSagaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SagaOrchestrator_GetSaga_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSagaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SagaOrchestratorServer).GetSaga(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SagaOrchestrator_GetSaga_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SagaOrchestratorServer).GetSaga(ctx, req.(*GetSagaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SagaOrchestrator_ListSagas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSagasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SagaOrchestratorServer).ListSagas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SagaOrchestrator_ListSagas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SagaOrchestratorServer).ListSagas(ctx, req.(*ListSagasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SagaOrchestrator_ServiceDesc is the grpc.ServiceDesc for SagaOrchestrator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SagaOrchestrator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "saga.v1.SagaOrchestrator",
	HandlerType: (*SagaOrchestratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSaga",
			Handler:    _SagaOrchestrator_CreateSaga_Handler,
		},
		{
			MethodName: "StartSaga",
			Handler:    _SagaOrchestrator_StartSaga_Handler,
		},
		{
			MethodName: "GetSaga",
			Handler:    _SagaOrchestrator_GetSaga_Handler,
		},
		{
			MethodName: "ListSagas",
			Handler:    _SagaOrchestrator_ListSagas_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/saga/v1/saga.proto",
}
