// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: proto/saga/v1/saga.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SagaStatus int32

const (
	SagaStatus_SAGA_STATUS_UNSPECIFIED  SagaStatus = 0
	SagaStatus_SAGA_STATUS_PENDING      SagaStatus = 1
	SagaStatus_SAGA_STATUS_RUNNING      SagaStatus = 2
	SagaStatus_SAGA_STATUS_COMPENSATING SagaStatus = 3
	SagaStatus_SAGA_STATUS_COMPLETED    SagaStatus = 4
	SagaStatus_SAGA_STATUS_FAILED       SagaStatus = 5
	// SAGA_STATUS_ABORTED is set by the AbortSaga RPC. Terminal state.
	// NOTE: pb.go regeneration is deferred until the proto toolchain is set up.
	SagaStatus_SAGA_STATUS_ABORTED SagaStatus = 6
)

// Enum value maps for SagaStatus.
var (
	SagaStatus_name = map[int32]string{
		0: "SAGA_STATUS_UNSPECIFIED",
		1: "SAGA_STATUS_PENDING",
		2: "SAGA_STATUS_RUNNING",
		3: "SAGA_STATUS_COMPENSATING",
		4: "SAGA_STATUS_COMPLETED",
		5: "SAGA_STATUS_FAILED",
		6: "SAGA_STATUS_ABORTED",
	}
	SagaStatus_value = map[string]int32{
		"SAGA_STATUS_UNSPECIFIED":  0,
		"SAGA_STATUS_PENDING":      1,
		"SAGA_STATUS_RUNNING":      2,
		"SAGA_STATUS_COMPENSATING": 3,
		"SAGA_STATUS_COMPLETED":    4,
		"SAGA_STATUS_FAILED":       5,
		"SAGA_STATUS_ABORTED":      6,
	}
)

func (x SagaStatus) Enum() *SagaStatus {
	p := new(SagaStatus)
	*p = x
	return p
}

func (x SagaStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SagaStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_saga_v1_saga_proto_enumTypes[0].Descriptor()
}

func (SagaStatus) Type() protoreflect.EnumType {
	return &file_proto_saga_v1_saga_proto_enumTypes[0]
}

func (x SagaStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SagaStatus.Descriptor instead.
func (SagaStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_saga_v1_saga_proto_rawDescGZIP(), []int{0}
}

type StepStatus int32

const (
	StepStatus_STEP_STATUS_UNSPECIFIED         StepStatus = 0
	StepStatus_STEP_STATUS_PENDING             StepStatus = 1
	StepStatus_STEP_STATUS_RUNNING             StepStatus = 2
	StepStatus_STEP_STATUS_SUCCEEDED           StepStatus = 3
	StepStatus_STEP_STATUS_FAILED              StepStatus = 4
	StepStatus_STEP_STATUS_COMPENSATING        StepStatus = 5
	StepStatus_STEP_STATUS_COMPENSATED         StepStatus = 6
	StepStatus_STEP_STATUS_COMPENSATION_FAILED StepStatus = 7
)

// Enum value maps for StepStatus.
var (
	StepStatus_name = map[int32]string{
		0: "STEP_STATUS_UNSPECIFIED",
		1: "STEP_STATUS_PENDING",
		2: "STEP_STATUS_RUNNING",
		3: "STEP_STATUS_SUCCEEDED",
		4: "STEP_STATUS_FAILED",
		5: "STEP_STATUS_COMPENSATING",
		6: "STEP_STATUS_COMPENSATED",
		7: "STEP_STATUS_COMPENSATION_FAILED",
	}
	StepStatus_value = map[string]int32{
		"STEP_STATUS_UNSPECIFIED":         0,
		"STEP_STATUS_PENDING":             1,
		"STEP_STATUS_RUNNING":             2,
		"STEP_STATUS_SUCCEEDED":           3,
		"STEP_STATUS_FAILED":              4,
		"STEP_STATUS_COMPENSATING":        5,
		"STEP_STATUS_COMPENSATED":         6,
		"STEP_STATUS_COMPENSATION_FAILED": 7,
	}
)

func (x StepStatus) Enum() *StepStatus {
	p := new(StepStatus)
	*p = x
	return p
}

func (x StepStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StepStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_saga_v1_saga_proto_enumTypes[1].Descriptor()
}

func (StepStatus) Type() protoreflect.EnumType {
	return &file_proto_saga_v1_saga_proto_enumTypes[1]
}

func (x StepStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StepStatus.Descriptor instead.
func (StepStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_saga_v1_saga_proto_rawDescGZIP(), []int{1}
}

type StepDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable step name; must be unique within a saga.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// URL the orchestrator POSTs to when executing the step.
	ForwardUrl string `protobuf:"bytes,2,opt,name=forward_url,json=forwardUrl,proto3" json:"forward_url,omitempty"`
	// URL the orchestrator POSTs to when compensating the step.
	CompensateUrl string `protobuf:"bytes,3,opt,name=compensate_url,json=compensateUrl,proto3" json:"compensate_url,omitempty"`
	// Maximum seconds to wait for a step HTTP response (0 = server default).
	TimeoutSeconds int32 `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StepDefinition) Reset() {
	*x = StepDefinition{}
	mi := &file_proto_saga_v1_saga_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepDefinition) ProtoMessage() {}

func (x *StepDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_saga_v1_saga_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepDefinition.ProtoReflect.Descriptor instead.
func (*StepDefinition) Descriptor() ([]byte, []int) {
	return file_proto_saga_v1_saga_proto_rawDescGZIP(), []int{0}
}

func (x *StepDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StepDefinition) GetForwardUrl() string {
	if x != nil {
		return x.ForwardUrl
	}
	return ""
}

func (x *StepDefinition) GetCompensateUrl() string {
	if x != nil {
		return x.CompensateUrl
	}
	return ""
}

func (x *StepDefinition) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type StepExecution struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status      StepStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=saga.v1.StepStatus" json:"status,omitempty"`
	Error       string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	StartedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	// error_detail is a JSON-encoded StepError with structured context for failed
	// steps (HTTP status code, response body excerpt, network error flag,
	// duration). Present only when status is FAILED or COMPENSATION_FAILED.
	ErrorDetail   []byte `protobuf:"bytes,6,opt,name=error_detail,json=errorDetail,proto3" json:"error_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepExecution) Reset() {
	*x = StepExecution{}
	mi := &file_proto_saga_v1_saga_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepExecution) ProtoMessage() {}

func (x *StepExecution) ProtoReflect() protoreflect.Message {
	mi := &file_proto_saga_v1_saga_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepExecution.ProtoReflect.Descriptor instead.
func (*StepExecution) Descriptor() ([]byte, []int) {
	return file_proto_saga_v1_saga_proto_rawDescGZIP(), []int{1}
}

func (x *StepExecution) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StepExecution) GetStatus() StepStatus {
	if x != nil {
		return x.Status
	}
	return StepStatus_STEP_STATUS_UNSPECIFIED
}

func (x *StepExecution) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StepExecution) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *StepExecution) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *StepExecution) GetErrorDetail() []byte {
	if x != nil {
		return x.ErrorDetail
	}
	return nil
}

type SagaExecution struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status SagaStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=saga.v1.SagaStatus" json:"status,omitempty"`
	Steps  []*StepExecution       `protobuf:"bytes,4,rep,name=steps,proto3" json:"steps,omitempty"`
	// Opaque payload forwarded verbatim to every step and compensation endpoint.
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	FailedStep    string                 `protobuf:"bytes,6,opt,name=failed_step,json=failedStep,proto3" json:"failed_step,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SagaExecution) Reset() {
	*x = SagaExecution{}
	mi := &file_proto_saga_v1_saga_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SagaExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SagaExecution) ProtoMessage() {}

func (x *SagaExecution) ProtoReflect() protoreflect.Message {
	mi := &file_proto_saga_v1_saga_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SagaExecution.ProtoReflect.Descriptor instead.
func (*SagaExecution) Descriptor() ([]byte, []int) {
	return file_proto_saga_v1_saga_proto_rawDescGZIP(), []int{2}
}

func (x *SagaExecution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SagaExecution) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SagaExecution) GetStatus() SagaStatus {
	if x != nil {
		return x.Status
	}
	return SagaStatus_SAGA_STATUS_UNSPECIFIED
}

func (x *SagaExecution) GetSteps() []*StepExecution {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *SagaExecution) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SagaExecution) GetFailedStep() string {
	if x != nil {
		return x.FailedStep
	}
	return ""
}

func (x *SagaExecution) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SagaExecution) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *SagaExecution) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type CreateSagaRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Steps   []*StepDefinition      `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	Payload []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// saga_timeout_seconds is the per-saga execution deadline in seconds.
	// If non-zero it overrides the server-wide SAGA_TIMEOUT_SECONDS env var.
	// Valid range: 1–86400 (24 h). Zero means use the server default.
	SagaTimeoutSeconds int32 `protobuf:"varint,4,opt,name=saga_timeout_seconds,json=sagaTimeoutSeconds,proto3" json:"saga_timeout_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateSagaRequest) Reset() {
	*x = CreateSagaRequest{}
	mi := &file_proto_saga_v1_saga_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSagaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSagaRequest) ProtoMessage() {}

func (x *CreateSagaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_saga_v1_saga_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSagaRequest.ProtoReflect.Descriptor instead.
func (*CreateSagaRequest) Descriptor() ([]byte, []int) {
	return file_proto_saga_v1_saga_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSagaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSagaRequest) GetSteps() []*StepDefinition {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *CreateSagaRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CreateSagaRequest) GetSagaTimeoutSeconds() int32 {
	if x != nil {
		return x.SagaTimeoutSeconds
	}
	return 0
}

type CreateSagaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Saga          *SagaExecution         `protobuf:"bytes,1,opt,name=saga,proto3" json:"saga,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSagaResponse) Reset() {
	*x = CreateSagaResponse{}
	mi := &file_proto_saga_v1_saga_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSagaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSagaResponse) ProtoMessage() {}

func (x *CreateSagaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_saga_v1_saga_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSagaResponse.ProtoReflect.Descriptor instead.
func (*CreateSagaResponse) Descriptor() ([]byte, []int) {
	return file_proto_saga_v1_saga_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSagaResponse) GetSaga() *SagaExecution {
	if x != nil {
		return x.Saga
	}
	return nil
}

type StartSagaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SagaId        string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSagaRequest) Reset() {
	*x = StartSagaRequest{}
	mi := &file_proto_saga_v1_saga_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSagaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSagaRequest) ProtoMessage() {}

func (x *StartSagaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_saga_v1_saga_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSagaRequest.ProtoReflect.Descriptor instead.
func (*StartSagaRequest) Descriptor() ([]byte, []int) {
	return file_proto_saga_v1_saga_proto_rawDescGZIP(), []int{5}
}

func (x *StartSagaRequest) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

type StartSagaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Saga          *SagaExecution         `protobuf:"bytes,1,opt,name=saga,proto3" json:"saga,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSagaResponse) Reset() {
	*x = StartSagaResponse{}
	mi := &file_proto_saga_v1_saga_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSagaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSagaResponse) ProtoMessage() {}

func (x *StartSagaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_saga_v1_saga_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSagaResponse.ProtoReflect.Descriptor instead.
func (*StartSagaResponse) Descriptor() ([]byte, []int) {
	return file_proto_saga_v1_saga_proto_rawDescGZIP(), []int{6}
}

func (x *StartSagaResponse) GetSaga() *SagaExecution {
	if x != nil {
		return x.Saga
	}
	return nil
}

type GetSagaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SagaId        string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSagaRequest) Reset() {
	*x = GetSagaRequest{}
	mi := &file_proto_saga_v1_saga_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSagaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSagaRequest) ProtoMessage() {}

func (x *GetSagaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_saga_v1_saga_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSagaRequest.ProtoReflect.Descriptor instead.
func (*GetSagaRequest) Descriptor() ([]byte, []int) {
	return file_proto_saga_v1_saga_proto_rawDescGZIP(), []int{7}
}

func (x *GetSagaRequest) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

type GetSagaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Saga          *SagaExecution         `protobuf:"bytes,1,opt,name=saga,proto3" json:"saga,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSagaResponse) Reset() {
	*x = GetSagaResponse{}
	mi := &file_proto_saga_v1_saga_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSagaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSagaResponse) ProtoMessage() {}

func (x *GetSagaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_saga_v1_saga_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSagaResponse.ProtoReflect.Descriptor instead.
func (*GetSagaResponse) Descriptor() ([]byte, []int) {
	return file_proto_saga_v1_saga_proto_rawDescGZIP(), []int{8}
}

func (x *GetSagaResponse) GetSaga() *SagaExecution {
	if x != nil {
		return x.Saga
	}
	return nil
}

type ListSagasRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter by status; unspecified = return all.
	Status        SagaStatus `protobuf:"varint,1,opt,name=status,proto3,enum=saga.v1.SagaStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSagasRequest) Reset() {
	*x = ListSagasRequest{}
	mi := &file_proto_saga_v1_saga_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSagasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSagasRequest) ProtoMessage() {}

func (x *ListSagasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_saga_v1_saga_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSagasRequest.ProtoReflect.Descriptor instead.
func (*ListSagasRequest) Descriptor() ([]byte, []int) {
	return file_proto_saga_v1_saga_proto_rawDescGZIP(), []int{9}
}

func (x *ListSagasRequest) GetStatus() SagaStatus {
	if x != nil {
		return x.Status
	}
	return SagaStatus_SAGA_STATUS_UNSPECIFIED
}

type ListSagasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sagas         []*SagaExecution       `protobuf:"bytes,1,rep,name=sagas,proto3" json:"sagas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSagasResponse) Reset() {
	*x = ListSagasResponse{}
	mi := &file_proto_saga_v1_saga_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSagasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSagasResponse) ProtoMessage() {}

func (x *ListSagasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_saga_v1_saga_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSagasResponse.ProtoReflect.Descriptor instead.
func (*ListSagasResponse) Descriptor() ([]byte, []int) {
	return file_proto_saga_v1_saga_proto_rawDescGZIP(), []int{10}
}

func (x *ListSagasResponse) GetSagas() []*SagaExecution {
	if x != nil {
		return x.Sagas
	}
	return nil
}

type AbortSagaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SagaId        string                 `protobuf:"bytes,1,opt,name=saga_id,json=sagaId,proto3" json:"saga_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortSagaRequest) Reset() {
	*x = AbortSagaRequest{}
	mi := &file_proto_saga_v1_saga_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortSagaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortSagaRequest) ProtoMessage() {}

func (x *AbortSagaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_saga_v1_saga_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortSagaRequest.ProtoReflect.Descriptor instead.
func (*AbortSagaRequest) Descriptor() ([]byte, []int) {
	return file_proto_saga_v1_saga_proto_rawDescGZIP(), []int{11}
}

func (x *AbortSagaRequest) GetSagaId() string {
	if x != nil {
		return x.SagaId
	}
	return ""
}

type AbortSagaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Saga          *SagaExecution         `protobuf:"bytes,1,opt,name=saga,proto3" json:"saga,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortSagaResponse) Reset() {
	*x = AbortSagaResponse{}
	mi := &file_proto_saga_v1_saga_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortSagaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortSagaResponse) ProtoMessage() {}

func (x *AbortSagaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_saga_v1_saga_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortSagaResponse.ProtoReflect.Descriptor instead.
func (*AbortSagaResponse) Descriptor() ([]byte, []int) {
	return file_proto_saga_v1_saga_proto_rawDescGZIP(), []int{12}
}

func (x *AbortSagaResponse) GetSaga() *SagaExecution {
	if x != nil {
		return x.Saga
	}
	return nil
}

var File_proto_saga_v1_saga_proto protoreflect.FileDescriptor

const file_proto_saga_v1_saga_proto_rawDesc = "" +
	"\n" +
	"\x18proto/saga/v1/saga.proto\x12\asaga.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x95\x01\n" +
	"\x0eStepDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vforward_url\x18\x02 \x01(\tR\n" +
	"forwardUrl\x12%\n" +
	"\x0ecompensate_url\x18\x03 \x01(\tR\rcompensateUrl\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\"\x83\x02\n" +
	"\rStepExecution\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\x06status\x18\x02 \x01(\x0e2\x13.saga.v1.StepStatusR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12!\n" +
	"\ferror_detail\x18\x06 \x01(\fR\verrorDetail\"\xfe\x02\n" +
	"\rSagaExecution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12+\n" +
	"\x06status\x18\x03 \x01(\x0e2\x13.saga.v1.SagaStatusR\x06status\x12,\n" +
	"\x05steps\x18\x04 \x03(\v2\x16.saga.v1.StepExecutionR\x05steps\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x1f\n" +
	"\vfailed_step\x18\x06 \x01(\tR\n" +
	"failedStep\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\xa2\x01\n" +
	"\x11CreateSagaRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12-\n" +
	"\x05steps\x18\x02 \x03(\v2\x17.saga.v1.StepDefinitionR\x05steps\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x120\n" +
	"\x14saga_timeout_seconds\x18\x04 \x01(\x05R\x12sagaTimeoutSeconds\"@\n" +
	"\x12CreateSagaResponse\x12*\n" +
	"\x04saga\x18\x01 \x01(\v2\x16.saga.v1.SagaExecutionR\x04saga\"+\n" +
	"\x10StartSagaRequest\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\"?\n" +
	"\x11StartSagaResponse\x12*\n" +
	"\x04saga\x18\x01 \x01(\v2\x16.saga.v1.SagaExecutionR\x04saga\")\n" +
	"\x0eGetSagaRequest\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\"=\n" +
	"\x0fGetSagaResponse\x12*\n" +
	"\x04saga\x18\x01 \x01(\v2\x16.saga.v1.SagaExecutionR\x04saga\"?\n" +
	"\x10ListSagasRequest\x12+\n" +
	"\x06status\x18\x01 \x01(\x0e2\x13.saga.v1.SagaStatusR\x06status\"A\n" +
	"\x11ListSagasResponse\x12,\n" +
	"\x05sagas\x18\x01 \x03(\v2\x16.saga.v1.SagaExecutionR\x05sagas\"+\n" +
	"\x10AbortSagaRequest\x12\x17\n" +
	"\asaga_id\x18\x01 \x01(\tR\x06sagaId\"?\n" +
	"\x11AbortSagaResponse\x12*\n" +
	"\x04saga\x18\x01 \x01(\v2\x16.saga.v1.SagaExecutionR\x04saga*\xc5\x01\n" +
	"\n" +
	"SagaStatus\x12\x1b\n" +
	"\x17SAGA_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SAGA_STATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13SAGA_STATUS_RUNNING\x10\x02\x12\x1c\n" +
	"\x18SAGA_STATUS_COMPENSATING\x10\x03\x12\x19\n" +
	"\x15SAGA_STATUS_COMPLETED\x10\x04\x12\x16\n" +
	"\x12SAGA_STATUS_FAILED\x10\x05\x12\x17\n" +
	"\x13SAGA_STATUS_ABORTED\x10\x06*\xee\x01\n" +
	"\n" +
	"StepStatus\x12\x1b\n" +
	"\x17STEP_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13STEP_STATUS_PENDING\x10\x01\x12\x17\n" +
	"\x13STEP_STATUS_RUNNING\x10\x02\x12\x19\n" +
	"\x15STEP_STATUS_SUCCEEDED\x10\x03\x12\x16\n" +
	"\x12STEP_STATUS_FAILED\x10\x04\x12\x1c\n" +
	"\x18STEP_STATUS_COMPENSATING\x10\x05\x12\x1b\n" +
	"\x17STEP_STATUS_COMPENSATED\x10\x06\x12#\n" +
	"\x1fSTEP_STATUS_COMPENSATION_FAILED\x10\a2\xe3\x02\n" +
	"\x10SagaOrchestrator\x12E\n" +
	"\n" +
	"CreateSaga\x12\x1a.saga.v1.CreateSagaRequest\x1a\x1b.saga.v1.CreateSagaResponse\x12B\n" +
	"\tStartSaga\x12\x19.saga.v1.StartSagaRequest\x1a\x1a.saga.v1.StartSagaResponse\x12<\n" +
	"\aGetSaga\x12\x17.saga.v1.GetSagaRequest\x1a\x18.saga.v1.GetSagaResponse\x12B\n" +
	"\tListSagas\x12\x19.saga.v1.ListSagasRequest\x1a\x1a.saga.v1.ListSagasResponse\x12B\n" +
	"\tAbortSaga\x12\x19.saga.v1.AbortSagaRequest\x1a\x1a.saga.v1.AbortSagaResponseB4Z2github.com/ngaddam369/saga-conductor/proto/saga/v1b\x06proto3"

var (
	file_proto_saga_v1_saga_proto_rawDescOnce sync.Once
	file_proto_saga_v1_saga_proto_rawDescData []byte
)

func file_proto_saga_v1_saga_proto_rawDescGZIP() []byte {
	file_proto_saga_v1_saga_proto_rawDescOnce.Do(func() {
		file_proto_saga_v1_saga_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_saga_v1_saga_proto_rawDesc), len(file_proto_saga_v1_saga_proto_rawDesc)))
	})
	return file_proto_saga_v1_saga_proto_rawDescData
}

var file_proto_saga_v1_saga_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_saga_v1_saga_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_saga_v1_saga_proto_goTypes = []any{
	(SagaStatus)(0),               // 0: saga.v1.SagaStatus
	(StepStatus)(0),               // 1: saga.v1.StepStatus
	(*StepDefinition)(nil),        // 2: saga.v1.StepDefinition
	(*StepExecution)(nil),         // 3: saga.v1.StepExecution
	(*SagaExecution)(nil),         // 4: saga.v1.SagaExecution
	(*CreateSagaRequest)(nil),     // 5: saga.v1.CreateSagaRequest
	(*CreateSagaResponse)(nil),    // 6: saga.v1.CreateSagaResponse
	(*StartSagaRequest)(nil),      // 7: saga.v1.StartSagaRequest
	(*StartSagaResponse)(nil),     // 8: saga.v1.StartSagaResponse
	(*GetSagaRequest)(nil),        // 9: saga.v1.GetSagaRequest
	(*GetSagaResponse)(nil),       // 10: saga.v1.GetSagaResponse
	(*ListSagasRequest)(nil),      // 11: saga.v1.ListSagasRequest
	(*ListSagasResponse)(nil),     // 12: saga.v1.ListSagasResponse
	(*AbortSagaRequest)(nil),      // 13: saga.v1.AbortSagaRequest
	(*AbortSagaResponse)(nil),     // 14: saga.v1.AbortSagaResponse
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_proto_saga_v1_saga_proto_depIdxs = []int32{
	1,  // 0: saga.v1.StepExecution.status:type_name -> saga.v1.StepStatus
	15, // 1: saga.v1.StepExecution.started_at:type_name -> google.protobuf.Timestamp
	15, // 2: saga.v1.StepExecution.completed_at:type_name -> google.protobuf.Timestamp
	0,  // 3: saga.v1.SagaExecution.status:type_name -> saga.v1.SagaStatus
	3,  // 4: saga.v1.SagaExecution.steps:type_name -> saga.v1.StepExecution
	15, // 5: saga.v1.SagaExecution.created_at:type_name -> google.protobuf.Timestamp
	15, // 6: saga.v1.SagaExecution.started_at:type_name -> google.protobuf.Timestamp
	15, // 7: saga.v1.SagaExecution.completed_at:type_name -> google.protobuf.Timestamp
	2,  // 8: saga.v1.CreateSagaRequest.steps:type_name -> saga.v1.StepDefinition
	4,  // 9: saga.v1.CreateSagaResponse.saga:type_name -> saga.v1.SagaExecution
	4,  // 10: saga.v1.StartSagaResponse.saga:type_name -> saga.v1.SagaExecution
	4,  // 11: saga.v1.GetSagaResponse.saga:type_name -> saga.v1.SagaExecution
	0,  // 12: saga.v1.ListSagasRequest.status:type_name -> saga.v1.SagaStatus
	4,  // 13: saga.v1.ListSagasResponse.sagas:type_name -> saga.v1.SagaExecution
	4,  // 14: saga.v1.AbortSagaResponse.saga:type_name -> saga.v1.SagaExecution
	5,  // 15: saga.v1.SagaOrchestrator.CreateSaga:input_type -> saga.v1.CreateSagaRequest
	7,  // 16: saga.v1.SagaOrchestrator.StartSaga:input_type -> saga.v1.StartSagaRequest
	9,  // 17: saga.v1.SagaOrchestrator.GetSaga:input_type -> saga.v1.GetSagaRequest
	11, // 18: saga.v1.SagaOrchestrator.ListSagas:input_type -> saga.v1.ListSagasRequest
	13, // 19: saga.v1.SagaOrchestrator.AbortSaga:input_type -> saga.v1.AbortSagaRequest
	6,  // 20: saga.v1.SagaOrchestrator.CreateSaga:output_type -> saga.v1.CreateSagaResponse
	8,  // 21: saga.v1.SagaOrchestrator.StartSaga:output_type -> saga.v1.StartSagaResponse
	10, // 22: saga.v1.SagaOrchestrator.GetSaga:output_type -> saga.v1.GetSagaResponse
	12, // 23: saga.v1.SagaOrchestrator.ListSagas:output_type -> saga.v1.ListSagasResponse
	14, // 24: saga.v1.SagaOrchestrator.AbortSaga:output_type -> saga.v1.AbortSagaResponse
	20, // [20:25] is the sub-list for method output_type
	15, // [15:20] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_saga_v1_saga_proto_init() }
func file_proto_saga_v1_saga_proto_init() {
	if File_proto_saga_v1_saga_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_saga_v1_saga_proto_rawDesc), len(file_proto_saga_v1_saga_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_saga_v1_saga_proto_goTypes,
		DependencyIndexes: file_proto_saga_v1_saga_proto_depIdxs,
		EnumInfos:         file_proto_saga_v1_saga_proto_enumTypes,
		MessageInfos:      file_proto_saga_v1_saga_proto_msgTypes,
	}.Build()
	File_proto_saga_v1_saga_proto = out.File
	file_proto_saga_v1_saga_proto_goTypes = nil
	file_proto_saga_v1_saga_proto_depIdxs = nil
}
